//
// Created by Andrei García on 8/12/20.
//

#ifndef PROYECTO_PRINCIPAL_MODIFIED_ACTION_H
#define PROYECTO_PRINCIPAL_MODIFIED_ACTION_H
enum Action {COPY, GAUSS, SOBEL};
#endif //PROYECTO_PRINCIPAL_MODIFIED_ACTION_H
